# Generated by Django 5.0.6 on 2024-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodelss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password1', models.IntegerField()),
                ('password2', models.IntegerField()),
            ],
        ),
    ]
