# Generated by Django 5.0.6 on 2024-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_alter_usermodelss_options_alter_usermodelss_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelss',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodelss',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usermodelss',
            name='password1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodelss',
            name='password2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodelss',
            name='user_permissions',
            field=models.ManyToManyField(null=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='usermodelss',
            name='username',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
