# Generated by Django 5.0.6 on 2024-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_usermodelss_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelss',
            name='username',
            field=models.CharField(max_length=800, null=True, unique=True),
        ),
    ]
