# Generated by Django 5.0.6 on 2024-06-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_usermodelss_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelss',
            name='username',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
